import fs from 'node:fs/promises';
import sharp from 'sharp';
await fs.mkdir('public/assets',{recursive:true});
await fs.mkdir('public/artworks',{recursive:true});
const source=process.argv[2];
if(source)await sharp(source).resize({width:2400,withoutEnlargement:true}).webp({quality:88}).toFile('public/assets/autumn.webp');
const designs=[['deib','DEIB','탐험 워크숍','DIVERSITY & INCLUSION','#08634d','#80e6b0'],['warm','온(溫)워크','과정','WELLBEING AT WORK','#a63f28','#ffceab'],['phone','폰 서비스','Skill-Up','COMMUNICATION','#be286f','#ffdbe9'],['ai','AI Work','Smart','FUTURE OF WORK','#184e90','#a9dbff'],['growth','다음의','가능성','LEARNING & GROWTH','#3c336f','#d9c8ff'],['together','함께,','더 멀리','PEOPLE & CULTURE','#a77d17','#ffebaf']];
for(const [i,d]of designs.entries()){const[id,a,b,category,color,accent]=d;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="760" viewBox="0 0 1200 760"><rect width="1200" height="760" fill="${color}"/><path d="M900 130h200v500H650" fill="none" stroke="${accent}" opacity=".15" stroke-width="90"/><path d="M880 355l110-110 110 110M990 248v280" fill="none" stroke="${accent}" stroke-width="4"/><text x="75" y="95" fill="${accent}" font-family="Arial,sans-serif" font-size="22" letter-spacing="4">EXPERT / ${category.replaceAll('&','&amp;')}</text><text x="70" y="300" fill="${accent}" font-family="Arial,Malgun Gothic,sans-serif" font-size="100" font-weight="700" letter-spacing="-4">${a}</text><text x="70" y="425" fill="${accent}" font-family="Arial,Malgun Gothic,sans-serif" font-size="100" font-weight="700" letter-spacing="-4">${b}</text><path d="M75 590h1050" stroke="${accent}" opacity=".4"/><text x="75" y="669" fill="${accent}" font-family="Arial,sans-serif" font-size="19" letter-spacing="3">PEOPLE. LEARNING. POSSIBILITY.</text><text x="1070" y="672" fill="${accent}" font-family="Arial,sans-serif" font-size="24">0${i+1}</text></svg>`;await fs.writeFile(`public/artworks/${id}.svg`,svg);}
const pkg=JSON.parse(await fs.readFile('package.json','utf8'));pkg.name='expert-virtual-gallery';pkg.scripts={...pkg.scripts,dev:'vite --config vite.static.config.js',build:'vite build --config vite.static.config.js',preview:'vite preview --config vite.static.config.js --host 127.0.0.1',bake:'node scripts/bake.mjs',test:'playwright test'};await fs.writeFile('package.json',JSON.stringify(pkg,null,2)+'\n');
await fs.writeFile('.openai/hosting.json',JSON.stringify({static:{directory:'dist'}},null,2)+'\n');
